### ISSUE TITLE
Mic stop recording after 1 min

### ISSUE THREAD

**Issue by wiiznokes** [teamclouday/AndroidMic#14]
The service seems to pause itself after 1 min when the app is minimized.
Then if we reopen the app, the stream work as expected.

**Comment by teamclouday** [comment]
Was the phone screen locked? I just tested on main branch and the minimized app does not affect the service.\
But if the phone was locked, the service was dead, until I unlock the phone. And this is because that foreground service (which sends audio data) was dead when the activity is down for a while.

**Comment by wiiznokes** [comment]
When the phone screen is unlocked.

**Comment by teamclouday** [comment]
Hmm... this will be hard to debug. Could you double click on the audio display to hide it and then test with minimized app?\
My quick guess is that the GUI rendering was turned off while the app was updating the audio waves.

**Comment by wiiznokes** [comment]
I figured out what was the problem.
We need to specified the service will use microphone as is mentioned [here ](https://developer.android.com/guide/components/foreground-services#types).
So just add `startForeground(FOREGROUND_SERVICE_TYPE_MICROPHONE, notification` in `onCreate `of `ForegroundService` will solve the issue.

**Comment by wiiznokes** [comment]
Just tried and it's work even better as expect (even when the screen is locked)

**Comment by teamclouday** [comment]
Sounds great! I'll try it.
